### PR TITLE
chore: update examples to use Deno.serve + bump std

### PR DESCRIPTION
**Pull request by lino-levan**

### CODE REVIEW

**Comment by lino-levan** [comment]
Just wanted to note that I realized these were outdated when reviewing https://github.com/denoland/deno/pull/19805.

**Review by crowlKats — APPROVED** [review]

**Review by idanran — APPROVED** [review]
LGTM

**Comment by idanran** [comment]
https://dash.deno.com/playground/example-helloworld

What to do here?

**Comment by lino-levan** [comment]
That's up to deno deploy team afaik

**Comment by idanran** [comment]
> That's up to deno deploy team afaik

Okay.

**Pull request merged**
