### PR TITLE
Removed the note that it requires read permission.

### PR DESCRIPTION
**Pull request by DavidPesta**

### CODE REVIEW

**Review by satyarohith — COMMENTED** [review]
Please update the `@run --allow-read --allow-write` command on line 5.

**Comment by lino-levan** [comment]
@DavidPesta could you update the comment at the top of the file?

**Comment by DavidPesta** [comment]
Yep, got it. Let me know if there is anything else.

**Comment by lino-levan** [comment]
LGTM, pinging @kt3k for a look at this

**Review by kt3k — APPROVED** [review]
Confirmed the example works without `--allow-read`

LGTM

**Pull request merged**
