### PR TITLE
feat: add copy button

### PR DESCRIPTION
**Pull request by lino-levan**
closes https://github.com/denoland/denobyexample/issues/27

### CODE REVIEW

**Review by crowlKats — CHANGES_REQUESTED** [review]
Seems unnecessary to pull-in doc_components for just an icon. you can either copy the icon declaration from it, or use an icon from https://tabler-icons-tsx.deno.dev/

**Comment by lino-levan** [comment]
If you insist. Does this look good?

**Review by kt3k — APPROVED** [review]
LGTM

**Comment by lino-levan** [comment]
@crowlKats PTAL!

**Review by crowlKats — APPROVED** [review]
LGTM

**Pull request merged**
