### PR TITLE
chore: update dependencies in examples

### PR DESCRIPTION
**Pull request by lino-levan**

### CODE REVIEW

**Comment by lino-levan** [comment]
It looks like format command has changed since this was last updated. I will make a commit formatting it, but I did not change the files with the bad formatting so /shrug

**Comment by lino-levan** [comment]
@lucacasonato any ideas why byexample is failing to deploy?

**Comment by kt3k** [comment]
@lino-levan Can you resolve the conflicts?

**Comment by crowlKats** [comment]
Errors should be fixed if rebased on latest main

**Review by kt3k — APPROVED** [review]
LGTM

**Pull request merged**
