### PR TITLE
fix: stop disabling user selection of snippet text

### PR DESCRIPTION
**Pull request by not-my-profile**
Not being able to select text is annoying.

### CODE REVIEW

**Comment by lino-levan** [comment]
The issue with this is that it now becomes impossible the select text in the code block. It is unfortunate, but I think we need to reorganize how the website is architected.

**Comment by not-my-profile** [comment]
Ah right, good call. I'll look into how the CSS layout could be changed to accommodate selection in both columns.

**Comment by not-my-profile** [comment]
I don't think it's possible to improve the selection behavior of the current two column layout without negatively impacting accessibility. I guess the best option would be to abandon the two-column layout and just display the comments and the code in a linear fashion (like the current mobile layout).

**Comment by lino-levan** [comment]
It's definitely possible, but quite a large pain to do so. I haven't gotten around to doing it because of that.

**Comment by not-my-profile** [comment]
Oh really? What solution do you have in mind? The reason I am not so sure about it is that I think that screen readers determine the order in a similar manner as the text selection does.

**Comment by lino-levan** [comment]
Ah, that is indeed troublesome. From an accessibility perspective, should screen readers even read code? If so, wouldn't it make sense to read all of the text first THEN the code? Not sure.

**Comment by not-my-profile** [comment]
Yes screen readers should (and do) certainly read code. And no reading all the text first would be bad since the comments are very much related to the next piece of code.

As I said I think the best solution is to abandon the two-column layout. As a sighted user I don't even find it particularly comfortable to read since your eyes have to follow the page in a very unusual snake pattern.

**Pull request closed without merging**
