### PR TITLE
chore: update fresh version 1.4.3

### LINKED ISSUE #98: Import map diagnostics warning
`deno task test` says this:

```
Import map diagnostics:
  - Invalid top-level key "tasks". Only "imports" and "scopes" can be present.
  - Invalid top-level key "compilerOptions". Only "imports" and "scopes" can be present.
```

looks like importing `www/deno.json` from `deno.jsonc` caused this warning:

>   "importMap": "./www/deno.json",

### PR DESCRIPTION
**Pull request by hashrock**
Close #98 

I created import_map.json to share imports between root and www directories. I would like to solve this problem with deno.json if possible though.

### CODE REVIEW

**Review by lino-levan — APPROVED** [review]
The importmap will most likely get crushed into `deno.jsonc` if we run the upgrade script, but other than that this PR does solve the problem. Thanks for looking into it Hashrock!

**Review by kt3k — APPROVED** [review]
LGTM

**Comment by kt3k** [comment]
BTW I wonder if it's good idea to merge `root` and `www`. (Non fresh code looks very small)

**Comment by hashrock** [comment]
I think it's good idea! let's do that in another PR

**Pull request merged**
