### PR TITLE
feat: dns queries

### PR DESCRIPTION
**Pull request by lino-levan**

### CODE REVIEW

**Comment by crowlKats** [comment]
I wonder if we should have an example for this; there is the line of something being on denobyexample and something being an example in the docs.

**Comment by kt3k** [comment]
@crowlKats 

> I wonder if we should have an example for this; there is the line of something being on denobyexample and something being an example in the docs.

You mean this is too niche to be listed here? BTW this is on the list of the initial plan #5

**Comment by crowlKats** [comment]
yea, I think we should rather write more examples in the docs directly (https://deno.land/api@v1.29.4?unstable&s=Deno.resolveDns). Though I forgot about #5.

**Comment by lino-levan** [comment]
I'm okay with going either way on this one. I've just been going down the list on #5.

**Comment by lino-levan** [comment]
For an update, @crowlKats (on discord) said:
> i mean, as said [earlier], i think its fine to merge

Just confirming that this is still accurate?

**Review by kt3k — APPROVED** [review]
I'm in favor of landing this.

I agree we should proritize the examples in the JSDocs, but it's not harmful to have this example here as well.

Some users might prefer to find the features from this site and it'll be more discoverable to such users.

**Comment by lino-levan** [comment]
Just a small note: I thought this PR would interact badly with #50 but it looks like I was wrong and these should be land-able in any order.

**Pull request merged**
