### PR TITLE
Group articles

### LINKED ISSUE #63: Group articles
I would like to have categories on the top page for readability. It would be easier to read if there are no more than 7 articles per category.

I asked Bing AI to classify them. Some of the classifications are wrong though.

```
[It seems like these articles are related to Deno, which is a runtime environment for JavaScript and TypeScript](https://deno.land/)[1](https://deno.land/)[2](https://ja.wikipedia.org/wiki/Deno). I can try to categorize and group them based on their topics. Here is one possible way:

- Introduction: Hello World
- Basics: Logging with colors, Importing & Exporting, Dependency Management, Benchmarking
- Data Formats: Importing JSON, Parsing and serializing JSON, Parsing and serializing TOML, Parsing and serializing YAML
- Encoding & Hashing: Hex and Base64 Encoding, Hashing
- Timers: Timeouts & Intervals
- User Interaction: Input Prompts
- Runtime Information: Getting the Deno version, Permission Management, Process Information, Handling OS Signals
- System Interaction: Environment Variables, Command Line Arguments
- File System: Reading Files, Writing Files, Moving/Renaming Files, Temporary Files & Directories, Creating & Removing Directories, Watching the filesystem, Walking directories, Checking for file existence
- Web Development: Web Workers, Web Assembly, Manipulating byte arrays, HTTP Requests, Running DNS Queries, Generating & Validating UUIDs, Subprocesses: Collecting Output, HTTP Server: Hello World, HTTP Server: Routing, HTTP Server: Streaming, HTTP Server: Serving Files, TCP Listener: Ping, TCP Connector: Ping

Is this what you were looking for?
```

I would add, "CLI" and "Network". Ideas?

### PR DESCRIPTION
**Pull request by hashrock**
Close #63 

Still looks too simplified. Maybe we could use tailwind3's columnar layout.

image

I would like to hear your opinion on this classification.

https://github.com/denoland/denobyexample/pull/64/files#diff-04dac91d97ef600ade75880cf9f12ee6dc5d4cbe758c65e31ada285bfcef8d03

### CODE REVIEW

**Comment by hashrock** [comment]
Ugh, Type Error within tests.
If anyone knows of a solution, please let me know.

```
TS2300 [ERROR]: Duplicate identifier 'URLPattern'.
declare class URLPattern {
              ~~~~~~~~~~
    at asset:///lib.deno.url.d.ts:259:15

    'URLPattern' was also declared here.
    declare class URLPattern {
                  ~~~~~~~~~~
        at asset:///lib.dom.extras.d.ts:80:15
```

**Comment by lino-levan** [comment]
Haven't looked into the type error yet but just have a comment on design. This requires a lot of scrolling, could we potentially put these in a CSS grid or flex box with wrapping or something? I think it would be nice to be able to see multiple categories horizontally!

**Comment by hashrock** [comment]
Yes, I was thinking of using twind's column layout. I'd have to update fresh to do that😅
We could certainly do it with flex-wrap.

**Comment by lucacasonato** [comment]
Looks great. What about `--no-remote` to fix the type checking?

**Comment by hashrock** [comment]
got error by `--no-remote`:

```
error: A remote specifier was requested: "https://deno.land/std@0.175.0/testing/asserts.ts", but --no-remote is specified.
    at file:///C:/code/gh-desktop/denoland/denobyexample/www/utils/example_test.ts:1:44
```

this error was happen in `deno test`, so I'm not sure we can solve by `--no-remote`.
I've tested with `--no-check` and it works. `--no-check=remote` could not fix the error.

**Comment by hashrock** [comment]
I've fixed the error with a band-aid, but I'd like to fix the type-checking settings if possible.

**Comment by lino-levan** [comment]
I do like the grouping better now that there are rows, but it feels a little off, could you try shifting these around?
Screenshot 2023-03-12 at 2 19 02 PM

**Comment by lino-levan** [comment]
> I've fixed the error with a band-aid, but I'd like to fix the type-checking settings if possible.

It feels weird to me that we're getting type checking errors. It's almost like we're specifying `deno.ns` twice somewhere?

**Comment by hashrock** [comment]
I also tried column layouts. The margins are a little less clean, but better than before.

image

**Comment by kt3k** [comment]
Looks like we need to change the base typings for testing https://github.com/denoland/denobyexample/pull/64/commits/91aa5a1eadd8740def97ccb4459490f5a2491489

**Review by kt3k — APPROVED** [review]
LGTM

**Comment by hashrock** [comment]
Thank you kt3k!

**Pull request merged**
